{% set name = "objprint" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/objprint-{{ version }}.tar.gz
  sha256: f617bed110c18c3b0f63b29b1b6609e41bc864c563ec8a35ef6c0cbea0070da2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - objprint
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gaogaotiantian/objprint
  summary: A library that can print Python objects in human readable format
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
